### ISSUE TITLE
CenterContent doesn't work on img the first time they're loaded

### ISSUE THREAD

**Issue by Dugnychon** [KensingtonTech/ngx-panzoom#34]
**Describe the bug**
When using CenterContent on an image, the content won't be centered until the image has been cached the browser. The first time it will center the top left corner, and a refresh will allow the content to be centered.

**Reduced Test Case**
Here is a simple stackblitz: https://stackblitz.com/edit/ng2-panzoom-test-100

**To Reproduce**
1. Go to https://stackblitz.com/edit/ng2-panzoom-test-100
2. Click on the center button
3. See the content not being centered
4. Refresh. If the same image is served from cache, it will center correctly.

You can swap the img src to a static image like https://via.placeholder.com/350x150 to see the problem on the first load 

**Expected behavior**
The content should be centered, or the user of the lib should be able to call a function to compute the size of the content after it has been loaded.

**Screenshots**
Here is a screenshot of the image not being centered 
![image](https://user-images.githubusercontent.com/1116720/90839313-3161a780-e325-11ea-87de-39130e7537e4.png)

**Desktop :**
 - OS: Windows 10 2004
 - Browser Edge Chromium
 - Version Canary

 - Browser Firefox
 - Version 79.0

**Additional context**
I tried to implement such a thing myself, but was unable to with my limited knowledge of the internals of ng2-panzoom, and I'm unsure whether I've pinned down the problem right. If I'm mistaken and there is an easy fix in my code, I'd be glad too!

**Comment by KensingtonTech** [comment]
@Dugnychon I knokw what the problem is.  I'll have a solution tomorrow, hopefully.  I may add an API method to recalculate the content size, or I could add a ResizeObserver.  Or both.

**Comment by KensingtonTech** [comment]
@Dugnychon I'm guessing that this factor is probably an unknown in your case, but if you already know the size of the image, you can just enclose it in a div with the height and width set.

**Comment by Dugnychon** [comment]
> @Dugnychon I know what the problem is. I'll have a solution tomorrow, hopefully. I may add an API method to recalculate the content size, or I could add a ResizeObserver. Or both.

@KensingtonTech  Nice! Thank you for that. I tried to simply update the contentWidth and contentHeight but it didn't seem to work on my case (if I haven't done anything wrong..)


> @Dugnychon I'm guessing that this factor is probably an unknown in your case, but if you already know the size of the image, you can just enclose it in a div with the height and width set.

Yes it is unfortunately of an unknown size in my situation...
