### ISSUE TITLE
[BUG] - ModelChanged isPanning flag doesn't correctly set to false

### ISSUE THREAD

**Issue by BenjaminMaiwald** [KensingtonTech/ngx-panzoom#35]
I encountered an issue with the panzoom library.
![IsPanningBug](https://user-images.githubusercontent.com/69507775/90961454-6a2a8980-e4a9-11ea-8e56-0fdfb03defaa.gif)
As seen in the gif from the official demo, panning an image does not correctly set isPanning to false every time the mouse is released.
So when the mouse is clicked and the image is being panned, is panning is always true, but once you release the mouse, it is set to false only occasionally.
IsPanning just staying on true, eventhough the user is currently not panning,  leads to various issues in our application, where we need to know if the image is actually being panned at the moment.
We tried this in Firefox (79.0 (64-Bit)), Safari (Version 13.1.2 (15609.3.5.1.3)) and Chrome( Version 84.0.4147.135 ) on linux ubuntu and mac os (10.15.6).

**Comment by KensingtonTech** [comment]
@BenjaminMaiwald Thanks for the bug report.  There will be a fix coming in the next few days, hopefully.

**Comment by KensingtonTech** [comment]
10.3.0, just released, should resolve this issue.  It also resolves a number of other issues with the isPanning property.

I'll leave this open for a day or two, should you run into any trouble.

**Comment by BenjaminMaiwald** [comment]
Thank you very much
