### ISSUE TITLE
Pinch zoom too slow on mobile devices

### ISSUE THREAD

**Issue by logicz** [KensingtonTech/ngx-panzoom#41]
I used the following config:

```
panZoomConfigOptions: PanZoomConfigOptions = {
    zoomLevels: 82,
    neutralZoomLevel: 41,
    initialZoomLevel: 0.02,
    scalePerZoomLevel: 1.05,
    zoomStepDuration: 0.02,
    freeMouseWheelFactor: 0.008,
    zoomToFitZoomLevelFactor: 1,
    dragMouseButton: 'left',
    dynamicContentDimensions: true
  };
```

On laptop everything works fine also with touchpad, slower then mouse wheel, but fine. On my android in chrome It's very, very slow.

I found a line in the component and see the constant that gives such effect:

`this.changeZoomLevel( this.base.zoomLevel + delta * 0.0001, clickPoint)`

Is it possible to have a config property like freeMouseWheelFactor to adjust sensibility of pinch zooming with big zoomlevel amount?

**Comment by logicz** [comment]
I used the following config:

```
panZoomConfigOptions: PanZoomConfigOptions = {
    zoomLevels: 82,
    neutralZoomLevel: 41,
    initialZoomLevel: 0.02,
    scalePerZoomLevel: 1.05,
    zoomStepDuration: 0.02,
    freeMouseWheelFactor: 0.008,
    zoomToFitZoomLevelFactor: 1,
    dragMouseButton: 'left',
    dynamicContentDimensions: true
  };
```
  
  On laptop everything works fine also with touchpad, slower then mouse wheel, but fine. On my android in chrome It's very, very slow.
  
I found a line in the component and see the constant that gives such effect:

`this.changeZoomLevel( this.base.zoomLevel + delta * 0.0001, clickPoint )`

Is it possible to have a config property like freeMouseWheelFactor to adjust sensibility of pinch zooming with big zoomlevel amount?

**Comment by KensingtonTech** [comment]
@logicz apologies for the long delay in responding.  Please refer to the section of the readme concerning support for mobile devices.  For your reference:

```I am actively soliciting pull requests for mobile support. Read on.

The library implements some basic support that may work with some mobile devices, though pinch-to-zoom still needs considerable work. As the application that this library was developed for was never intended for use with mobile devices, there are no plans to implement full mobile support. As long as this remains the case, I respecfully ask for no more issues concerning mobile support, please. I realise that this will limit adoption, but for an enterprising developer out there, I can't imagine that adding mobile support would be nearly as big of a challenge as it was to port the library to Angular from AngularJS!```
