### ISSUE TITLE
[BUG] - Config is private

### ISSUE THREAD

**Issue by giovanni-venturelli** [KensingtonTech/ngx-panzoom#45]
When compiling, angular11 returns the following error:
error TS2341: Property 'config' is private and only accessible within class 'PanZoomComponent'.

Unluckily I couldn't reproduce it in stackblitz with angular 10
However the code is as simple as:

`<pan-zoom [config]="panZoomConfig">
  <app-my-element></app-my-element>
</pan-zoom>`

OS: Windows 10

Sorry I can't reproduce the problem in stackblitz but it really seems there's something wrong with the declaration of the property

**Comment by RichardC64** [comment]
Same here

**Comment by giovanni-venturelli** [comment]
I just downloaded the code and changed the property to public. I then realized I didn't need the library any longer, however.
