### ISSUE TITLE
unable to zoom out below 0 level

### ISSUE THREAD

**Issue by ravik3592** [KensingtonTech/ngx-panzoom#46]
I want to have zoom in, zoom out and fit to screen function.
I have implemented all those, but i was not able to zoom out below level 2 or 1. also after fit to screen, my zoom in is not working as per required ratio

**Comment by KensingtonTech** [comment]
@ravik3592 please resubmit using the issue template provided, including the Stackblitz reduced test case using the link provided in the template.
