### ISSUE TITLE
[BUG] - over-restrictive keepInBounds

### ISSUE THREAD

**Issue by ekorian** [KensingtonTech/ngx-panzoom#48]
**Describe the bug**
When you zoom on a corner of an image, you cannot mouse-drag to the other end of the image when keepInBounds is set to true, even though the image is still inside bounds. It seems like the bounds are not computed correctly when zoomed.

**Desktop (please complete the following information):**
 - OS: debian
 - Browser brave
 - Angular: 11.2.6

**Comment by KensingtonTech** [comment]
@ekorian Will you be providing a reduced test case, as requested in the issue template?  Or at least a brief video illustrating the issue?

**Comment by KensingtonTech** [comment]
@ekorian I'll be closing for now.  Feel free to open a new one if you have time to open an issue with a reduced test case or video illustrating the problem.
